// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: rockim/api/openapi/v1/auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AuthCodeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthCodeRequestMultiError, or nil if none found.
func (m *AuthCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetProductId()) < 1 {
		err := AuthCodeRequestValidationError{
			field:  "ProductId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAccount()) < 1 {
		err := AuthCodeRequestValidationError{
			field:  "Account",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AuthCodeRequestMultiError(errors)
	}

	return nil
}

// AuthCodeRequestMultiError is an error wrapping multiple validation errors
// returned by AuthCodeRequest.ValidateAll() if the designated constraints
// aren't met.
type AuthCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthCodeRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthCodeRequestMultiError) AllErrors() []error { return m }

// AuthCodeRequestValidationError is the validation error returned by
// AuthCodeRequest.Validate if the designated constraints aren't met.
type AuthCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthCodeRequestValidationError) ErrorName() string { return "AuthCodeRequestValidationError" }

// Error satisfies the builtin error interface
func (e AuthCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthCodeRequestValidationError{}

// Validate checks the field values on AuthCodeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *AuthCodeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthCodeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AuthCodeResponseMultiError, or nil if none found.
func (m *AuthCodeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthCodeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AuthCode

	// no validation rules for ExpireTime

	if len(errors) > 0 {
		return AuthCodeResponseMultiError(errors)
	}

	return nil
}

// AuthCodeResponseMultiError is an error wrapping multiple validation errors
// returned by AuthCodeResponse.ValidateAll() if the designated constraints
// aren't met.
type AuthCodeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthCodeResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthCodeResponseMultiError) AllErrors() []error { return m }

// AuthCodeResponseValidationError is the validation error returned by
// AuthCodeResponse.Validate if the designated constraints aren't met.
type AuthCodeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthCodeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthCodeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthCodeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthCodeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthCodeResponseValidationError) ErrorName() string { return "AuthCodeResponseValidationError" }

// Error satisfies the builtin error interface
func (e AuthCodeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthCodeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthCodeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthCodeResponseValidationError{}
